### ISSUE TITLE
htccondor release-current rpm doesn't exist anymore for EL9 (10.x channel)

### ISSUE THREAD

**Issue by antoine-m-01** [usegalaxy-eu/terraform#24]
Hi, 

In HTCondor deployment, the task "Add YUM repository for HTCondor" failed because 10.x/htcondor-release-current.el9.noarch.rpm doesn't exist.

As workaround, I configured the yum repository directly:
```
- name: Add repository for HTCondor
  ansible.builtin.yum_repository:
    name: HTCondor
    description: HTCondor YUM repo
    baseurl: https://research.cs.wisc.edu/htcondor/repo/{{ htcondor_channel }}/el{{ ansible_distribution_major_version }}/$basearch/release
```
(in ansible/roles/ansible-htcondor-grycap/tasks/RedHat.yaml).

Best regards, 
Antoine.
